
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyjtphsqtfdqrcsjzzoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5anRwaHNxdGZkcXJjc2p6em9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzM1MTcsImV4cCI6MjA1OTk0OTUxN30.7Dn27JSl0nHAvxRi-9ElDlHCnXLfCG_cQ7I5l27uiuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
