
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyjtphsqtfdqrcsjzzoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5anRwaHNxdGZkcXJjc2p6em9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzM1MTcsImV4cCI6MjA1OTk0OTUxN30.7Dn27JSl0nHAvxRi-9ElDlHCnXLfCG_cQ7I5l27uiuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define types for the new tables
export type RewardType = {
  id: string;
  user_id: string;
  name: string;
  description: string;
  icon: string;
  achieved: boolean;
  date_achieved: string;
  type: 'daily' | 'weekly' | 'milestone';
};

export type UserSettingsType = {
  id: string;
  user_id: string;
  dark_mode: boolean;
  notifications: boolean;
  email_notifications: boolean;
  use_metric_system: boolean;
  language: string;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add type extensions for our custom tables
declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    from<T extends 'rewards'>(table: T): any;
    from<T extends 'user_settings'>(table: T): any;
  }
}
